name: japan-station-terms
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy=2.4.4
  - pandas=3.0.2
  - matplotlib=3.10.8
  - scipy=1.17.1
  - scikit-learn=1.8.0
  - obspy=1.5.0
  - pip
  - pip:
      - openquake.engine==3.25.1
